version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: inventory-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER?error}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?error}
      - POSTGRES_DB=${POSTGRES_DB?error}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    profiles:
      - dockerDB
    

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: inventory-backend
    environment:
      - DB_HOST=${DB_HOST_DOCKER?error}
      - SERVER_PORT=${SERVER_PORT?error}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS?error}
    depends_on:
      postgres:
        condition: service_started
        required: false
    ports:
      - "8080:8080"
    profiles:
      - dockerDB
      - localDB

  frontend:
    build:
      context: ./Frontend
      args:
        - VITE_API_URL=${VITE_API_URL?error}
      dockerfile: Dockerfile
    container_name: inventory-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    profiles:
      - dockerDB
      - localDB

volumes:
  postgres_data:
