services:
  postgres:
    image: postgres:15-alpine
    container_name: inventory-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER?error}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?error}
      - POSTGRES_DB=${POSTGRES_DB?error}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    profiles:
      - dockerDB
  redis:
    image: redis:7-alpine
    container_name: inventory-redis
    ports:
      - "6379:6379"
    profiles:
      - dockerDB
  auth-service:
    build:
      context: ./AuthService
      dockerfile: Dockerfile
    container_name: inventory-auth
    environment:
      - DB_URL=jdbc:postgresql://postgres:5432/auth_db
      - DB_USERNAME=${POSTGRES_USER?error}
      - DB_PASSWORD=${POSTGRES_PASSWORD?error}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      postgres:
        condition: service_started
      redis:
        condition: service_started
    ports:
      - "8081:8081"
    profiles:
      - dockerDB
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: inventory-backend
    environment:
      - DB_HOST=${DB_HOST_DOCKER?error}
      - SERVER_PORT=${SERVER_PORT?error}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS?error}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - AUTH_JWKS_URL=http://auth-service:8081/api/v1/auth/.well-known/jwks.json
    depends_on:
      postgres:
        condition: service_started
      redis:
        condition: service_started
      auth-service:
        condition: service_started
    ports:
      - "8080:8080"
    profiles:
      - dockerDB
      - localDB
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: inventory-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    profiles:
      - dockerDB
      - localDB
volumes:
  postgres_data: